### ISSUE TITLE
1.16.5 - java.lang.NoSuchMethodError: 'org.bukkit.entity.Entity org.bukkit.World.spawn(org.bukkit.Location, java.lang.Class, java.util.function.Consumer)

### ISSUE THREAD

**Issue by Overwrite987** [Gecolay/GSit#125]
Bug - gsit command are not working on 1.16.5 

Error:
https://pastebin.com/P555nea3

How to reproduce:
1) Install paper 1.16.5
2) Install and run the plugin
3) Use /sit command
4) error

**Comment by Gecolay** [comment]
fixed with the latest version 1.5.5

**Comment by Overwrite987** [comment]
> fixed with the latest version 1.5.5

but uh... it is not...
